blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostFeed

app_name = 'blog'

urlpatterns = [
    # post views
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('feed/', LatestPostFeed(), name='post_feed'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap


sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from taggit.managers import TaggableManager
from django.db.models import Count


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset()\
                                            .filter(status='published')

class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published')
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                            choices=STATUS_CHOICES,
                            default='draft')
    tags = TaggableManager()

    class Meta:
        ordering = ('-publish', ) # append ',' to tell Python it's a tuple.

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                        args=[self.publish.year,
                                self.publish.month,
                                self.publish.day, self.slug])


    objects = models.Manager()
    published = PublishedManager()

    def get_similar_posts(self):
        '''
        Given a post object, it returns queryset of 4 posts that have same tags
        '''
        post_tags_ids = self.tags.values_list('id', flat=True) # flat=True makes returning object a list of one values not [( x,y )]
        similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=self.id)
        similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]
        return similar_posts




class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',) # ascending order (older to newer)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

param/models.py
from django.db import models


class IntegerParams(models.Model):
    name = models.CharField(max_length=50)
    value = models.IntegerField(verbose_name='Value')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name
    
    

blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
     class Meta:
         model = Comment
         fields = ('name', 'email', 'body')

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.core.paginator import (
    Paginator,
    EmptyPage,
    PageNotAnInteger
)
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm
from django.core.mail import send_mail
from django.contrib import messages
from taggit.models import Tag
from django.db.models import Count
from param.models import IntegerParams


# function-based view of post list
def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    BLOG_POSTS_PAGE_SIZE = get_object_or_404(IntegerParams, name='BLOG_POSTS_PAGE_SIZE').value

    paginator = Paginator(object_list, per_page=BLOG_POSTS_PAGE_SIZE)
    page_number = request.GET.get('page_number')
    try:
        posts = paginator.get_page(page_number)
    except  PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.get_page(1)
    except EmptyPage:
        # If page is out of range deliver the last page of results
        posts = paginator.get_page(paginator.num_pages)

    return render(request, 'blog/post/list.html', 
                        {
                            'posts': posts, 
                            'page_number': page_number, 
                            'range': range(1,paginator.num_pages+1),
                            'tag': tag
                        })

# # class-based views of post list
# class PostListView(ListView):
#     queryset = Post.published.all()
#     context_object_name = 'posts'
#     paginate_by = 2
#     template_name = 'blog/post/list.html'


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                                    status='published',
                                    publish__year=year,
                                    publish__month=month,
                                    publish__day=day)
    
    # List of active comments for this post
    comments = post.comments.filter(active=True)
    
    new_comment = None

    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but do not save to the database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
            comment_form = CommentForm()
            messages.success(request, 'You commented successfully')
    else:
        comment_form = CommentForm()

    # List of similar posts
    similar_posts = post.get_similar_posts()

    return render(request, 'blog/post/detail.html', 
                    {
                        'post': post, 
                        'comments': comments, 
                        'new_comment': new_comment, 
                        'comment_form': comment_form,
                        'similar_posts': similar_posts
                    })


def post_share(request, post_id):
    # Retrieve by post id by giving **kwargs
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    
    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Forms field passed validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            # ..send email
            subject = f'{cd["name"]} recommends you to read {post.title}'
            message = f'Read {post.title} at {post_url} \n {cd["name"]}\s comments: \n {cd["comments"]}'
            messages.success(request, 'Successfully sent')
            sent = send_mail(subject, message, 'admin@myblog.com', [cd["to"]])
            if sent:
                form = EmailPostForm()
    else:
        form = EmailPostForm()
    
    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})

param/views.py
from django.shortcuts import render

# Create your views here.

blog/templates/blog/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{% static "blog/css/bootstrap-united.min.css" %}">
    <!-- <link rel="stylesheet" href="{% static "blog/css/blog.css" %}"> -->
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap-sketchy.min.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/main.css' %}">
    <script src="https://kit.fontawesome.com/e4a558bbd3.js" crossorigin="anonymous"></script>
</head>
<body>
    <div id="content">
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <div 
                    {% if message.tags %} role="alert" class="alert alert-{{ message.tags }} alert-dismissible fade show"
                    {% endif %}>{{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endfor %}
        </ul>
    {% endif %}
        {% block content %}
        {% endblock %}
    </div>
    <div id="sidebar">
        <h2>My Blog</h2>
        <p>This is my blog. I've written {% total_posts %} posts so far.</p>
        <hr>
        <h4>RSS</h4>
        <p><a href="{% url 'blog:post_feed' %}">
            Subscribe to my RSS feed
        </a></p>
        <hr>
        <h4>Latest posts</h4>
        {% show_latest_posts 3 %}
        <hr>
        <h4>Most commented posts</h4>
        {% get_most_commented_posts 3 as most_commented_posts %}
        <ul>
            {% for post in most_commented_posts %}
                <li>
                    <a href="{{ post.get_absolute_url}}"> {{ post.title }} </a>
                </li>
            {% endfor %}
        </ul>
        {% block sidebar %}
        {% endblock %}
    </div>
    
    <!-- Bootstrap javascript links -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
</body>
</html>

blog/templates/blog/pagination.html
<!-- Pagination -->
<div class="row justify-content-between">
    <div class="col-8">
    </div>
    <div class="col-4">
        <div class="row">
            <div class="mr-1">
                {% if page.has_previous %}
                    <a class="btn btn-outline-secondary" href="?page_number={{page.previous_page_number}}">&laquo;</a>        
                {% endif %}
            </div>
            <div class="btn-group mr-1">
                <button type="button" class="btn btn-outline-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  {{page.number}}
                </button>
                <div class="dropdown-menu">
                        {% for n in range %}
                            <a class="dropdown-item" href="?page_number={{n}}">{{n}}</a>
                        {% endfor %}
                </div> 
            </div>
            <div class="mr-1">
            <a class="btn btn-light disabled" href="#"><strong>/</strong></a>          
            </div>
            <div class="mr-1">
            <a class="btn btn-outline-secondary" href="?page_number={{page.paginator.num_pages}}">{{page.paginator.num_pages}}</a>
            </div>
            <div mr-1>
            {% if page.has_next %}
                <a class="btn btn-outline-secondary" href="?page_number={{page.next_page_number}}">&raquo;</a>
            {% endif %}
            </div>
        </div>        
    </div>
  </div>

blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% load blog_tags %}

{% block title %} {{ post.title }} {% endblock %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="tags">Tags: {{ post.tags.all|join:", " }}</p>
    <p class="date">
        Published {{post.publish}} by {{post.author}}
    </p>
    <!-- {{post.body|linebreaks}} -->
    {{ post.body|markdown }}
    <a href="{% url 'blog:post_list' %}" class="btn btn-outline-info"><i class="fas fa-arrow-left"></i></a>
    <a href="{% url 'blog:post_share' post.id %}" class="btn btn-outline-info"><i class="fas fa-share-alt"></i></a>
    <button type="button" class="btn btn-outline-info" data-toggle="modal" data-target="#exampleModal">
        <i class="fas fa-comments"></i>
    </button>
    <hr>

    {% with comments.count as total_comments %}
    <h4>
        {{ total_comments }} comment{{total_comments|pluralize}}
    </h4>
    {% endwith %}

    {% for comment in comments %}
        <div class="comment">
            <p class="text-info">
                Comment {{ forloop.counter }} by {{ comment.name }}
            </p>
            <p class="text-info">
                {{ comment.body|linebreaks }}
            </p>
        </div>
    {% empty %}
        <p class="text-info">
            There are no comments yet.
        </p>
    {% endfor %}

    <!-- Button trigger modal -->
    <hr>

  
    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Add a new comment</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <div class="modal-body">
                <form action="" method="post">
                    {{ comment_form|crispy }}
                    {% csrf_token %}
                    <a class="btn btn-outline-info" href="{{ post.get_absolute_url }}">Back</a>
                    <button type="submit" class="btn btn-info">Add Comment</button>
                </form>            
            </div>
            <div class="modal-footer">
            <!-- <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button> -->
            <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
            </div>
        </div>
        </div>
    </div>



{% endblock %}

{% block sidebar %}
    <hr>

    <h2>Similar Posts</h2>
    {% for post in similar_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
    {% empty %}
        There are no similar posts yet.
    {% endfor %}

{% endblock %}

blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block title %}My Blog{% endblock %}


{% block content %}
    <h1>My Blog</h1>
    
    {% include 'blog/pagination.html' with page=posts %}
    
    {% if tag %}
        <h2>Posts tagged with "{{tag.name}}"</h2>
    {% endif %}

    {% for post in posts %}
        <div class="card">
            <div class="card-body">
                <!-- POST TITLE -->
                <h4 class="card-title"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
                <!-- POST SUBTITLE -->
                <h6 class="card-subtitle mb-2 text-muted">
                    Published {{ post.publish }} by {{ post.author }} <br>
                    Tags:
                    {% for tag in post.tags.all %}
                        <a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>
                        {% if not forloop.last %}, {% endif %}    
                    {% endfor %}
                </h6>
                <!-- POST BODY -->
                <p class="card-text">
                    <!-- {{ post.body|truncatewords:30|linebreaks }} -->
                    {{ post.body|markdown|truncatewords_html:30 }}
                </p>
                <!-- POST FOOTER -->
                {% with post.comments.count as total_comments %}
                    <p class="text-muted">
                        <a href="{{ post.get_absolute_url }}">{{total_comments}} comment{{total_comments|pluralize}} <i class="fas fa-comments"></i></a>
                        <a href="{% url 'blog:post_share' post.id %}"><i class="fas fa-share-alt"></i></a>
                    </p>
                {% endwith %}
            </div>
        </div>

    {% endfor %}

    {% include 'blog/pagination.html' with page=posts %}
{% endblock %}

blog/templates/blog/post/share.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Share a post
{% endblock %}

{% block content %}
    <h2>
        Share <a href="{{ post.get_absolute_url }}">{{ post.title }}</a> by email
    </h2>
    <hr>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <a href="{% url 'blog:post_list' %}" class="btn btn-outline-info">Cancel</a>
        <button type="submit" class="btn btn-info"> Send E-mail </button>  
    </form>

{% endblock %}